### 회원가입
POST localhost:8081/member/join
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "1234"
}


### 로그인
POST localhost:8081/member/login
Content-Type: application/json

{
"email": "test@naver.co",
"password": "1234"
}